### ISSUE TITLE
Modding toolkit doesnt work with 1.6.00.2+

### ISSUE THREAD

**Issue by RoshanGamer7791** [Stef-Moroyna/Spaceflight-Simulator--ModdingToolkit#3]
When you use the latest version of the modding toolkit it doesnt work for sfs 1.6.00.2+

**Comment by var863** [comment]
I thought It was in beta so any kind of modding is can't work on it

**Comment by Sam101Lol** [comment]
> I thought It was in beta so any kind of modding is can't work on it

modding should work on it, the issue is that the lastest version has compilation errors so we modders don´t have access to the shiny new modules
